export const MovieData = [
  {
    adult: false,
    backdrop_path: "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
    genre_ids: [27],
    id: 938614,
    original_language: "en",
    original_title: "Late Night with the Devil",
    overview:
      "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
    popularity: 598.016,
    poster_path:
      "https://image.tmdb.org/t/p/original/u3YQJctMzFN2wAvnkmXy41bXhFv.jpg",
    release_date: "2024-03-19",
    title: "Late Night with the Devil",
    trailer: "https://www.youtube.com/watch?v=VHXgNPuNsK4",
    video: false,
    vote_average: 7.325,
    vote_count: 257,
  },
  {
    adult: false,
    backdrop_path: "/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
    genre_ids: [18, 36],
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: "589.967",
    poster_path:
      "https://image.tmdb.org/t/p/original/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    trailer: "https://www.youtube.com/watch?v=O_hKC3gRvzw",
    video: false,
    vote_average: 8.11,
    vote_count: 7819,
  },
  {
    adult: false,
    backdrop_path: "/4CcUgdiGe83MeqJW1NyJVmZqRrF.jpg",
    genre_ids: [18, 10749],
    id: 937287,
    original_language: "en",
    original_title: "Challengers",
    overview:
      'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.',
    popularity: 574.924,
    poster_path:
      "https://image.tmdb.org/t/p/original/H6vke7zGiuLsz4v4RPeReb9rsv.jpg",
    release_date: "2024-04-18",
    title: "Challengers",
    trailer: "https://www.youtube.com/watch?v=usOvkpu4pWU",
    video: false,
    vote_average: 7.463,
    vote_count: 229,
  },
  {
    adult: false,
    backdrop_path: "/rVJfabCz1ViynQCEz54MRqdZig1.jpg",
    genre_ids: [16, 878, 28],
    id: 1155089,
    original_language: "en",
    original_title: "Justice League: Crisis on Infinite Earths Part One",
    overview:
      "Death is coming. Worse than death: oblivion. Not just for our Earth, but for everyone, everywhere, in every universe! Against this ultimate destruction, the mysterious Monitor has gathered the greatest team of Super Heroes ever assembled. But what can the combined might of Superman, Wonder Woman, Batman, The Flash, Green Lantern and hundreds of Super Heroes from multiple Earths even do to save all of reality from an unstoppable antimatter armageddon?!",
    popularity: 570.756,
    poster_path:
      "https://image.tmdb.org/t/p/original/zR6C66EDklgTPLHRSmmMt5878MR.jpg",
    release_date: "2024-01-08",
    title: "Justice League: Crisis on Infinite Earths Part One",
    trailer: "https://www.youtube.com/watch?v=VAv-JOAmHck",
    video: false,
    vote_average: 7.641,
    vote_count: 191,
  },
  {
    adult: false,
    backdrop_path: "/fypydCipcWDKDTTCoPucBsdGYXW.jpg",
    genre_ids: [878, 12, 28],
    id: 653346,
    original_language: "en",
    original_title: "Kingdom of the Planet of the Apes",
    overview:
      "Several generations in the future following Caesar's reign, apes are now the dominant species and live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all that he has known about the past and to make choices that will define a future for apes and humans alike.",
    popularity: 558.557,
    poster_path:
      "https://image.tmdb.org/t/p/original/zhyLLcwtvfNiFXDSZ2c5vOxLq2p.jpg",
    release_date: "2024-05-08",
    title: "Kingdom of the Planet of the Apes",
    trailer: "https://www.youtube.com/watch?v=Q45wW7AmgC0",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/dcnSWFCtk4b2aIzkhq6IDbzoIf1.jpg",
    genre_ids: [28, 35],
    id: 942047,
    original_language: "en",
    original_title: "Outsource",
    overview:
      "A police chief hires an old friend, who is an international spy, to help him search for a wanted suspect in the Philippines. When the chief dies, all evidence points towards the spy, and he must go to extremes to defend himself.",
    popularity: 558.256,
    poster_path:
      "https://image.tmdb.org/t/p/original/zIAF0UXtCJTJOYNYWiBfyifaaOi.jpg",
    release_date: "2022-01-18",
    title: "Outsource",
    trailer: "https://www.youtube.com/watch?v=FpinTIH-2AI",
    video: false,
    vote_average: 2.3,
    vote_count: 11,
  },
  {
    adult: false,
    backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
    genre_ids: [878, 12],
    id: 438631,
    original_language: "en",
    original_title: "Dune",
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    popularity: 532.362,
    poster_path:
      "https://image.tmdb.org/t/p/original/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    release_date: "2021-09-15",
    title: "Dune",
    trailer: "https://www.youtube.com/watch?v=QCScW8vVnB4",
    video: false,
    vote_average: 7.791,
    vote_count: 11443,
  },
  {
    adult: false,
    backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
    genre_ids: [28, 80, 53],
    id: 385687,
    original_language: "en",
    original_title: "Fast X",
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    popularity: 519.832,
    poster_path:
      "https://image.tmdb.org/t/p/original/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    release_date: "2023-05-17",
    title: "Fast X",
    trailer: "https://www.youtube.com/watch?v=Hwex9RNReP0",
    video: false,
    vote_average: 7.127,
    vote_count: 5095,
  },
  {
    adult: false,
    backdrop_path: "/cIztAxDn3H8JylRaJwiHHpkGe53.jpg",
    genre_ids: [10751, 35, 16],
    id: 1239146,
    original_language: "en",
    original_title: "Woody Woodpecker Goes to Camp",
    overview:
      "After getting kicked out of the forest, Woody thinks he's found a forever home at Camp Woo Hoo — until an inspector threatens to shut down the camp.",
    popularity: 508.871,
    poster_path:
      "https://image.tmdb.org/t/p/original/mMnzNYvpqLLLdgF5TMmXfuy6wzx.jpg",
    release_date: "2024-04-12",
    title: "Woody Woodpecker Goes to Camp",
    trailer: "https://www.youtube.com/watch?v=7Sj39US0hYI",
    video: false,
    vote_average: 6.845,
    vote_count: 100,
  },
];
